services:
  cooprog:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    links:
      - cooprog_server
      - cooprog_client
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  cooprog_client:
    image: ghcr.io/bleumatin-fr/cooprog/client:latest
    environment:
      - PORT=3000
      - NODE_ENV=production
      - API_URL=http://cooprog_server:3000/api
      - NEXT_PUBLIC_API_URL=https://cooprog.eu/api
      - NEXT_PUBLIC_NOMINATIM_API_URL=https://nominatim.openstreetmap.org
    restart: always
    links:
      - cooprog_server

  cooprog_server:
    image: ghcr.io/bleumatin-fr/cooprog/server:latest
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_URL=mongodb://root:password@cooprog_mongo:27017/admin
      - PASSWORD_SALT_ROUND=10
      - JWT_SECRET=secret
      - JWT_EXPIRY=60 * 1
      - REFRESH_TOKEN_SECRET=secret
      - REFRESH_TOKEN_EXPIRY=60 * 60 * 24 * 30
      - COOKIE_SECRET=secret
      - RESET_PASSWORD_TOKEN_SECRET=secret
      - RESET_PASSWORD_TOKEN_EXPIRY=60 * 60 * 24 * 30
      - INVITATION_TOKEN_EXPIRY=60 * 60 * 24 * 7
      - WHITELISTED_DOMAINS=https://cooprog.eu
      - MAIL_URL=smtps://user:password@domain:465
      - MAIL_FROM=no-reply@cooprog.eu
      - MAIL_TO=contact@cooprog.eu
      - FRONTEND_URL=https://cooprog.eu
      - ADMIN_URL=https://cooprog.eu/admin
      - CRON_SCHEDULE=30 6 * * *
      - CRON_WEEKLY_DIGEST_SCHEDULE=30 6 * * 1
      - CRON_MODERATION_SCHEDULE=0 8 * * *
      - LOGGER_FORMAT=json
      - UPLOAD_PATH=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    links:
      - cooprog_mongo

  cooprog_mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./.docker/mongo/data:/data/db
      - ./.docker/mongo/backup:/data/backup
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s

  cooprog_admin:
    image: ghcr.io/bleumatin-fr/cooprog/admin:latest
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
