events {
}

http {
    server {
        listen 80;
        server_name cooprog.eu;

        # To allow special characters in headers
        ignore_invalid_headers off;
        # Allow any size file to be uploaded.
        # Set to a value such as 1000m; to restrict file size to a specific value
        client_max_body_size 0;
        # To disable buffering
        proxy_buffering off;
        include /etc/nginx/mime.types;

        location / {
            proxy_pass http://cooprog_client:3000/;
        }

        location /api/ {
            proxy_pass http://cooprog_server:3000/api/;
        }

        location /admin {
            proxy_pass http://cooprog_admin/;
        }

        location /admin/api/ {
            proxy_pass http://cooprog_server:3000/admin/api/;
        }
    }
}